version: '3'
services:

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=cleep
      - RABBITMQ_DEFAULT_PASS=cleep
